"""añadiendo llaves foraneas a los modelos

Revision ID: 1f60829d0ab4
Revises: 27476d5dee03
Create Date: 2026-03-27 12:30:02.315301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f60829d0ab4'
down_revision: Union[str, Sequence[str], None] = '27476d5dee03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'flights', 'airports', ['destination_airport_id'], ['id'])
    op.create_foreign_key(None, 'flights', 'airports', ['origin_airport_id'], ['id'])
    op.create_foreign_key(None, 'flights', 'airlines', ['airline_id'], ['id'])
    op.create_foreign_key(None, 'passengers', 'reservations', ['reservation_id'], ['id'])
    op.create_foreign_key(None, 'reservation_flights', 'reservations', ['reservation_id'], ['id'])
    op.create_foreign_key(None, 'reservation_flights', 'flights', ['flight_id'], ['id'])
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.drop_constraint(None, 'reservation_flights', type_='foreignkey')
    op.drop_constraint(None, 'reservation_flights', type_='foreignkey')
    op.drop_constraint(None, 'passengers', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    # ### end Alembic commands ###
