"""Migracion inicial

Revision ID: 53c3ac11e09c
Revises: 
Create Date: 2026-03-27 21:55:16.338737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c3ac11e09c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('flights_airline_id_flight_number_departure_at_key'), 'flights', type_='unique')
    op.drop_index(op.f('idx_flights_destination_arrival'), table_name='flights')
    op.drop_index(op.f('idx_flights_origin_departure'), table_name='flights')
    op.create_unique_constraint('uq_flight_departure', 'flights', ['airline_id', 'flight_number', 'departure_at'])
    op.drop_constraint(op.f('flights_destination_airport_id_fkey'), 'flights', type_='foreignkey')
    op.drop_constraint(op.f('flights_airline_id_fkey'), 'flights', type_='foreignkey')
    op.drop_constraint(op.f('flights_origin_airport_id_fkey'), 'flights', type_='foreignkey')
    op.create_foreign_key(None, 'flights', 'airports', ['origin_airport_id'], ['id'])
    op.create_foreign_key(None, 'flights', 'airports', ['destination_airport_id'], ['id'])
    op.create_foreign_key(None, 'flights', 'airlines', ['airline_id'], ['id'])
    op.drop_index(op.f('idx_passengers_reservation'), table_name='passengers')
    op.drop_constraint(op.f('passengers_reservation_id_fkey'), 'passengers', type_='foreignkey')
    op.create_foreign_key(None, 'passengers', 'reservations', ['reservation_id'], ['id'])
    op.drop_index(op.f('idx_reservation_flights_flight'), table_name='reservation_flights')
    op.drop_index(op.f('idx_reservation_flights_reservation'), table_name='reservation_flights')
    op.drop_constraint(op.f('reservation_flights_reservation_id_flight_id_key'), 'reservation_flights', type_='unique')
    op.drop_constraint(op.f('reservation_flights_reservation_id_segment_order_key'), 'reservation_flights', type_='unique')
    op.create_unique_constraint('uq_reservation_flight', 'reservation_flights', ['reservation_id', 'flight_id'])
    op.create_unique_constraint('uq_reservation_segment', 'reservation_flights', ['reservation_id', 'segment_order'])
    op.drop_constraint(op.f('reservation_flights_flight_id_fkey'), 'reservation_flights', type_='foreignkey')
    op.drop_constraint(op.f('reservation_flights_reservation_id_fkey'), 'reservation_flights', type_='foreignkey')
    op.create_foreign_key(None, 'reservation_flights', 'reservations', ['reservation_id'], ['id'])
    op.create_foreign_key(None, 'reservation_flights', 'flights', ['flight_id'], ['id'])
    op.drop_index(op.f('idx_reservations_user_created'), table_name='reservations')
    op.drop_constraint(op.f('reservations_user_id_fkey'), 'reservations', type_='foreignkey')
    op.create_foreign_key(None, 'reservations', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False,
               existing_server_default=sa.text("'CLIENT'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'CLIENT'::text"))
    op.drop_constraint(None, 'reservations', type_='foreignkey')
    op.create_foreign_key(op.f('reservations_user_id_fkey'), 'reservations', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_index(op.f('idx_reservations_user_created'), 'reservations', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.drop_constraint(None, 'reservation_flights', type_='foreignkey')
    op.drop_constraint(None, 'reservation_flights', type_='foreignkey')
    op.create_foreign_key(op.f('reservation_flights_reservation_id_fkey'), 'reservation_flights', 'reservations', ['reservation_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('reservation_flights_flight_id_fkey'), 'reservation_flights', 'flights', ['flight_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_reservation_segment', 'reservation_flights', type_='unique')
    op.drop_constraint('uq_reservation_flight', 'reservation_flights', type_='unique')
    op.create_unique_constraint(op.f('reservation_flights_reservation_id_segment_order_key'), 'reservation_flights', ['reservation_id', 'segment_order'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('reservation_flights_reservation_id_flight_id_key'), 'reservation_flights', ['reservation_id', 'flight_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_reservation_flights_reservation'), 'reservation_flights', ['reservation_id'], unique=False)
    op.create_index(op.f('idx_reservation_flights_flight'), 'reservation_flights', ['flight_id'], unique=False)
    op.drop_constraint(None, 'passengers', type_='foreignkey')
    op.create_foreign_key(op.f('passengers_reservation_id_fkey'), 'passengers', 'reservations', ['reservation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_passengers_reservation'), 'passengers', ['reservation_id'], unique=False)
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.drop_constraint(None, 'flights', type_='foreignkey')
    op.create_foreign_key(op.f('flights_origin_airport_id_fkey'), 'flights', 'airports', ['origin_airport_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('flights_airline_id_fkey'), 'flights', 'airlines', ['airline_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('flights_destination_airport_id_fkey'), 'flights', 'airports', ['destination_airport_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint('uq_flight_departure', 'flights', type_='unique')
    op.create_index(op.f('idx_flights_origin_departure'), 'flights', ['origin_airport_id', 'departure_at'], unique=False)
    op.create_index(op.f('idx_flights_destination_arrival'), 'flights', ['destination_airport_id', 'arrival_at'], unique=False)
    op.create_unique_constraint(op.f('flights_airline_id_flight_number_departure_at_key'), 'flights', ['airline_id', 'flight_number', 'departure_at'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
